// Code generated by "stringer -type=CellType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Empty-0]
	_ = x[Text-1]
	_ = x[Number-2]
	_ = x[Expression-3]
	_ = x[Clone-4]
}

const _CellType_name = "EmptyTextNumberExpressionClone"

var _CellType_index = [...]uint8{0, 5, 9, 15, 25, 30}

func (i CellType) String() string {
	if i < 0 || i >= CellType(len(_CellType_index)-1) {
		return "CellType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CellType_name[_CellType_index[i]:_CellType_index[i+1]]
}
